### ISSUE TITLE
不支持CompletableFuture

### ISSUE THREAD

**Issue by cmershen1** [oldratlee/log4j2-ttl-thread-context-map#6]
我使用`log4j2-ttl-thread-context-map`实现线程间的请求链路跟踪。

发现每次使用`CompletableFuture`时，日志打出的`traceid`都是一样的，是否不支持`CompletableFuture`？

-----------

第一次请求，CompletableFuture和主线程的traceId同为A。
第二次请求，主线程的traceId是B，CompletableFuture开启的异步方法中traceId仍为A
……
以后所有的请求，CompletableFuture开启的异步方法中traceId都为A

**Comment by oldratlee** [comment]
方便分离一下问题，给一下 极简的、可运行复现问题的 测试Demo代码吗？

如果能写成个UT就更好了： @cmershen1  ❤️

- Fork这个仓库
- 添加一个 极简的可运行复现问题的 UT Case
